### ISSUE TITLE
[bug]: Generation routes with @PathParams

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#928]
### Describe the bug

If i use the `PathParam` in the constructor then I catch this message - The argument type 'String Function({required dynamic id})' can't be assigned to the parameter type 'String'. I cant update packages versions, plz fix this bugs.

### To reproduce
```dart
  stacked: ^3.2.1
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.1
  stacked_generator: ^1.1.0
```
```dart
const ClientCardView({
    @PathParam('id') required this.clientID,
    Key? key,
}) : super(key: key);
```
```dart
MaterialRoute(
    page: ClientCardView,
    name: 'clientCardViewRoute',
    path: '/clients/:id',
),
```

### Screenshots

<img width="666" alt="image" src="https://user-images.githubusercontent.com/20646071/231974914-c7c2ff6d-d256-4d0f-9c71-17f07ee32393.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/20646071/231974426-189aba57-7355-4e80-9cda-7115c2b69112.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/20646071/231976694-f8a2061a-e141-4780-8333-02b34a9b39fb.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/20646071/231976912-c70c7d77-361c-46cf-9411-eb07c3f7f218.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/20646071/231977854-d815da2e-dda9-4b40-832f-7c22fa10908c.png">

**Comment by FilledStacks** [comment]
Are you using the new Router functionality? or the v1 navigation service?

**Comment by ziqq** [comment]
> Are you using the new Router functionality? or the v1 navigation service?

```dart
  stacked: ^3.2.1
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.1
  stacked_generator: ^1.1.0
```

**Comment by FilledStacks** [comment]
Are you using the functionality shown in the latest stacked video on my channel, i.e. generating a stacked app using the `web` template in the cli, or the old functionality of using the `NavigationService`.

Stacked NavigationService is not built for web, it's built for native applications. We created new functionality in the latest version of stacked for the web which is the RouterService.

**Comment by ziqq** [comment]
> Are you using the functionality shown in the latest stacked video on my channel, i.e. generating a stacked app using the `web` template in the cli, or the old functionality of using the `NavigationService`.
> 
> Stacked NavigationService is not built for web, it's built for native applications. We created new functionality in the latest version of stacked for the web which is the RouterService.

Oh. I didn't see this video. I will try to view and send feedback. Thx! Plz don't delete this issue without me feedback.

**Comment by ziqq** [comment]
### 1. I migrated to new navigation from tutorial in your video and was fine but i catch one error

```dart
CustomRoute<ClientExtended?>(
  page: ContactsView,
  name: 'contactsView',
  customRouteBuilder: modalsPageRouteBuilder,
),
```

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233017745-0538a0a1-71b6-45ef-83ee-0cffb0af6093.png">

#### if i import the needed model

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233017950-526fc898-db2c-4a38-a659-09aaeeb2bbb7.png">

### 2. How can i use custom PageRouter?

From

```dart
ClientsListViewRoute.name: (routeData) {
  return _i37.MaterialPageX<dynamic>(
    routeData: routeData,
    child: const _i2.ClientsListView(),
  );
}
```
To

```dart
ClientsListViewRoute.name: (routeData) {
  return _i37.MaterialWithModalsPageRoute<dynamic>(
    routeData: routeData,
    child: const _i2.ClientsListView(),
  );
}
```

#### This is how I do it and so far it looks like. Please tell me I'm on the right track?

```dart
CustomRoute(
  page: SubscriptionManagementInnerView,
  name: 'subscriptionManagementInnerView',
  customRouteBuilder: modalsPageRoute,
),

Route<T> modalsPageRoute<T>(
  // ignore: avoid-unused-parameters
  BuildContext context,
  Widget child,
  CustomPage<T> page,
) {
  return MaterialWithModalsPageRoute(
    fullscreenDialog: page.fullscreenDialog,
    settings: page,
    builder: (_) => child,
  );
}
```

### 3. How i can get same currentRoute?

Before

```dart 
navigationService.currentRoute
```

###  4. How I can use dependencies in StackedApp with my config for **ApiService**? Can u suggest me how i can make like this not in **thirdparty_services_module**? Thx!

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  KeyValueStorageService get keyValueStorageService => KeyValueStorageService.getInstance();

  @LazySingleton(as: ApiConsumer)
  BBHttpClient getApiConsumer(
    KeyValueStorageService keyValueStorageService,
  ) {
    return BBHttpClient(
      baseUrl: '${dotenv.env[BaseUrlKey]}/api/',
      keyValueStorageService: keyValueStorageService,
      debug: dotenv.env[EnvKey] == DevelopmentModeKey,
    );
  }
}
```

### 5. I don't understand how to do in such cases. Can you suggest?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233274587-b9a2acec-9eb7-4d23-93c9-f6b8f3469a0e.png">

Like

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  FirebaseMessaging get firebaseMessaging => FirebaseMessaging.instance;
}
```

### 6. How to realize the `ExtendedNavigator`? I have main app and package authorization with different `router` & `locator` and `app.dart` file to.

StartUp View

```dart
ViewModelBuilder<AppViewModel>.reactive(
  viewModelBuilder: () => AppViewModel(),
  onViewModelReady: (viewModel) => viewModel.init(),
  builder: (context, viewModel, _) {
    if (viewModel.isBusy) {
      return const CustomLoadingView();
    }

    if (viewModel.data == AuthenticationStatus.unauthenticated) {
      return const AuthNavigator();
    }

    if (viewModel.data == AuthenticationStatus.authenticated) {
      return const MainView();
    }

    return const CustomLoadingView();
  },
)
```

Before
```dart
ExtendedNavigator(
  router: AuthNavigatorRouter(),
  initialRouteArgs: NestedAuthViewArguments(
    authType: authType,
    title: title,
    description: description,
  ),
  navigatorKey: StackedService.nestedNavigationKey(NestedNavigationKey),
),
```

#### What i can use like T?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233288774-a017a2eb-3c2b-4a9c-823b-b0ffc1f9a356.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233305302-0d3a8496-7990-4d45-b3b8-b90a1b330114.png">

Auth package locator

```dart
Future<void> setupLocator({
  required RootStackRouter router,
}) async {
  $initGetIt(locator);
  locator<RouterService>().setRouter(router);
}

static Future<void> initialise({
  required RootStackRouter router,
}) async {
  WidgetsFlutterBinding.ensureInitialized();
  await setupLocator(router: router);
}
```

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233305836-851b9c15-2372-4832-ae16-12f2db3b3356.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233306033-9de25d37-6cfc-485b-b2f7-24e2121b28d9.png">

#### I tried more variants

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233309837-4ffa9527-9ee5-478d-8ea4-c8ebcc5c9fd8.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233318780-5e8ab99b-e2f7-44e0-b803-d112ae2da264.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233375091-638bdee5-ce7c-4987-871b-e061a3d3792a.png">

**Comment by ziqq** [comment]
@FilledStacks I have some question plz get me answers if u can. Thx!

PS: The main question is related to `ExtendedNavigator`.

**Comment by FilledStacks** [comment]
If you use the latest router service with the additional `build.yaml` file in the root of the project then you should now have a widget called `NestedRouter` that's in the second video of the new Flutter web series 2023.

**Comment by ziqq** [comment]
> If you use the latest router service with the additional `build.yaml` file in the root of the project then you should now have a widget called `NestedRouter` that's in the second video of the new Flutter web series 2023.

Yap i use latest version, but `NestedRouter` produces the error shown above. I have auth module how placed in the **packages** not root directory. And i haven't auth routes in main app.dart, i placed the auth routes in auth package only. How i can do in this case? 

**My solution** - uses the `NavigationService` in auth package and uses old `ExtendedNavigator`, but in main app uses the `RouterService`. Like this it works.

**Comment by ziqq** [comment]
I found the error how bound with new `get_it` version

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/234267732-b38da4b4-d222-4f24-93af-afb9b06f53d2.png">

**Comment by FilledStacks** [comment]
Great. Its this fixed in the latest release?

**Comment by ziqq** [comment]
> Great. Its this fixed in the latest release?

About [this](https://github.com/Stacked-Org/stacked/issues/928#issuecomment-1521678693)? I have not yet tested it in the new version, at that time I used the latest available.

**Comment by FilledStacks** [comment]
Can I close this issue? Or is there still something required? This issue seems to be dealing with multiple things at the same time.

**Comment by ziqq** [comment]
> Can I close this issue? Or is there still something required? This issue seems to be dealing with multiple things at the same time.

### No. I still have any questions.

### How i can get same currentRoute?

Before

```dart 
navigationService.currentRoute
```

###  How I can use dependencies in StackedApp with my config for **ApiService**? Can u suggest me how i can make like this not in **thirdparty_services_module**? Thx!

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  KeyValueStorageService get keyValueStorageService => KeyValueStorageService.getInstance();

  @LazySingleton(as: ApiConsumer)
  BBHttpClient getApiConsumer(
    KeyValueStorageService keyValueStorageService,
  ) {
    return BBHttpClient(
      baseUrl: '${dotenv.env[BaseUrlKey]}/api/',
      keyValueStorageService: keyValueStorageService,
      debug: dotenv.env[EnvKey] == DevelopmentModeKey,
    );
  }
}
```

### I don't understand how to do in such cases. Can you suggest?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233274587-b9a2acec-9eb7-4d23-93c9-f6b8f3469a0e.png">

Like

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  FirebaseMessaging get firebaseMessaging => FirebaseMessaging.instance;
}
```

**Comment by FilledStacks** [comment]
Those questions are different than the original. 

Please open up an issue with one question in each so it's easier to respond to.
