### ISSUE TITLE
[bug]: ../../.pub-cache/hosted/pub.dev/stacked_shared-1.3.1/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.

### ISSUE THREAD

**Issue by vinodlee** [Stacked-Org/stacked#933]
### Describe the bug

../../.pub-cache/hosted/pub.dev/stacked_shared-1.3.1/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.

### To reproduce

../../.pub-cache/hosted/pub.dev/stacked_shared-1.3.1/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.

### Expected behavior

../../.pub-cache/hosted/pub.dev/stacked_shared-1.3.1/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.

### Screenshots

<img width="1284" alt="Screenshot 2023-04-25 at 5 50 34 PM" src="https://user-images.githubusercontent.com/22536559/234275105-169eab0f-ab6d-4d2d-9514-b0220bb56047.png">

**Comment by ziqq** [comment]
downgrade `get_it` to `7.2.0`

**Comment by mmustafasesudia** [comment]
same, also app.locator.dart not generating

**Comment by ziqq** [comment]
> same, also app.locator.dart not generating

Solution [above](https://github.com/Stacked-Org/stacked/issues/933#issuecomment-1521720392)

**Comment by sqrg** [comment]
> > same, also app.locator.dart not generating
> 
> Solution [above](https://github.com/Stacked-Org/stacked/issues/933#issuecomment-1521720392)

Downgrade to what exactly

**Comment by santhoshvgts** [comment]
yes, downgrade to what version

**Comment by ziqq** [comment]
> Downgrade to what exactly

> yes, downgrade to what version

`get_it: 7.2.0`

**Comment by chrisvidal** [comment]
same issue since 2 days.

how do you downgrade `get_it` please since it is embedded in `stacked` package?

**Comment by sqrg** [comment]
I think you would need to do a dependency override, explained here: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by KPatel91** [comment]
I am running version 7.2.0 of `get-it` but still facing the same issue.

**Comment by penguin86** [comment]
> I am running version 7.2.0 of get-it but still facing the same issue.

Same here

**Comment by ziqq** [comment]
> I am running version 7.2.0 of `get-it` but still facing the same issue.

try to clear pub cache and get more info of your packages versions

**Comment by FilledStacks** [comment]
Hey, is this still happening? 

Do you have the latest version of the generator and stacked?

**Comment by ziqq** [comment]
> Hey, is this still happening?
> 
> Do you have the latest version of the generator and stacked?

#### Yes, is this still happening. And yes i use latest versions.

<img width="750" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/de99ae82-3d12-4776-b9be-c8d4866a0272">

**Comment by BilalAsif25** [comment]
Guys help it suddenly happened to me too, i don't know why is this issue occurring

**Comment by mmustafasesudia** [comment]
`  get_it: 7.2.0`

Hopes this help

**Comment by avinashseth** [comment]
Solution

File location(Windows): C:\Users\MY_USER_NAME\AppData\Local\Pub\Cache\hosted\pub.dev\stacked_core-1.2.4\lib\src\code_generation\locator\stacked_locator.dart

Line # 405

```
locator.resetLazySingleton<T>(
        // instance: instance, <----------------- error code
        instance: instance as T?, <-------------  fixed code
        instanceName: instanceName,
        disposingFunction: disposingFunction,
);
```

**Comment by csandovalgt** [comment]
> ` get_it: 7.2.0`
> 
> Hopes this help

this worked for me

**Comment by FilledStacks** [comment]
This should be fixed with the latest generator and stacked versions. 

We don't use `stacked_core` anymore, it's now `stacked_shared` so the package you're using is the old ones.

**Comment by FilledStacks** [comment]
`stacked: ^3.2.5`
`stacked_generator: ^1.3.3`

**Comment by ziqq** [comment]
> `stacked: ^3.2.5` `stacked_generator: ^1.3.3`

@FilledStacks, It's not working form me.
I use latests versions and remove and clear .pub-cache.

<img width="600" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/48671a5b-6d27-4a2f-bbaa-17eedbdbaeaa">

<img width="600" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/9bac38e0-5a96-470f-adca-abcc0e260788">

<img width="600" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/e94320de-286a-4e79-b6f5-c64d0ca2a666">

**Comment by guiguito** [comment]
I do still get the problem. But it seems to come from stacked_themes dependency. Do we still use stacked_core instead of stacked_shared in stacked_themes @FilledStacks ?

**Comment by FilledStacks** [comment]
@guiguito most likely we do. We haven't updated themes in a while. Let me push an update for that.

**Comment by FilledStacks** [comment]
Try with themes 0.3.11 I just released it.

**Comment by guiguito** [comment]
sorry for my late reply. It works! @FilledStacks . Thank you so much for your reactivity.
